---
title: "Benedict Monteiro's CV"
author: Benedict Monteiro
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
geometry: "left=0cm,right=0cm,top=0cm,bottom=0cm"
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions_mine.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1WC2VQGbxqxsNcU06x1DMvFBV2AQZg1BCzF26pKs5qCE/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online [here](https://benedict909.github.io/)")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/benedict909/CV/raw/master/Benedict_Monteiro_CV.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available at [github.com/benedict909/CV](https://github.com/benedict909/CV).

Last updated on `r Sys.Date()`.



Main
================================================================================
\vspace{-30mm} Benedict Monteiro {#title}
--------------------------------------------------------------------------------

<!-- # ```{r} -->
<!-- # # Note the special double pipe so we modify the CV object in place -->
<!-- # CV %<>% print_text_block("intro")  -->
<!-- # ``` -->

<!-- find data-icons here: https://fontawesome.com/icons -->


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')
```



<!-- Work Experience {data-icon=suitcase} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('industy_experience_aside') -->
<!-- ``` -->
<!-- ::: -->

<!-- ```{r} -->
<!-- CV %<>% print_section('industry_positions') -->
<!-- ``` -->

<!-- These breaks just force a new page so section doesnt get cut off -->
<!-- <br> -->
<!-- <br> -->
<!-- <br> -->


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching_positions')
```



Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```


